micronaut:
  application:
    name: release-bot

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true
        default_schema: public
        physical_naming_strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

datasources:
  default:
    url: jdbc:postgresql://${DB_HOST:0.0.0.0}/release
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    db-type: postgresql
    dialect: POSTGRES
    maximum-pool-size: 10
    connection-timeout: 15000

jpa:
  default:
    entity-scan:
      packages: it.petrovich.bots.release.infrastructure.model

release:
  cron: 0 */1 * * * * # each minute

notification:
  cron: "*/30 * * * * *" # each 30 seconds
  telegram:
    releases:
      token: ${BOT_TOKEN}
      username: ${BOT_USERNAME}
      chats: ${TG_CHATS}