micronaut:
  application:
    name: release-bot
  server:
    port: 8965

datasources:
  default:
    url: jdbc:postgresql://${DB_HOST:0.0.0.0}/release
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    db-type: postgresql
    dialect: POSTGRES
    maximum-pool-size: 10
    connection-timeout: 15000

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/changelog/db.changelog-master.yaml'

jpa:
  default:
    entity-scan:
      packages: it.petrovich.bots.release.infrastructure.model
    properties:
      physical_naming_strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
      implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      hibernate:
        format-sql: true
        default_schema: public

release:
  cron: "0 */1 * * * *" # each minute

notification:
  cron: "*/30 * * * * *" # each 30 seconds
  telegram:
    releases:
      token: ${BOT_TOKEN}
      username: ${BOT_USERNAME}
      chats: ${TG_CHATS}