version: '3.1'
services:
  postgres:
    container_name: release-postgres
    build:
      context: ./db/postgres
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 6s
      retries: 10
