name: "Build and deploy application"
on:
  push:
    branches:
      - master
      - release
      - main
jobs:
  deploy:
    name: Deploy and restart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build jar
        run: |
          mvn clean package && cp target/release-bot.jar release-bot.jar

      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "release-bot.jar"
          target: "/opt/release-bot/source"
      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            systemctl stop release-bot
            mv /opt/release-bot/source/release-bot-latest.jar /opt/release-bot/source/release-bot-old.jar || true
            mv /opt/release-bot/source/release-bot.jar /opt/release-bot/source/release-bot-latest.jar
            systemctl start release-bot
            rm /opt/release-bot/source/release-bot-old.jar || true
