name: "Build and deploy application"
on:
  push:
    branches:
      - master
      - release
      - main
jobs:
  build:
    name: Build executable jar
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup jdk17
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 17
      - name: Build jar
        run: mvn package

  publish:
    name: Publish - GitHub Packages
    runs-on: ubuntu-18.04
    needs: [build]

    steps:
      - uses: actions/checkout@v1
      - name: Setup jdk17
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 17
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

