name: "Build and deploy application"
on:
  push:
    branches:
      - master
      - release
      - main
jobs:
  deploy:
    name: Deploy and restart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup java 17
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Build jar
        run: |
          ./gradlew assemble && cp build/libs/release-bot.jar release-bot.jar
      - name: Upload application
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "release-bot.jar"
          target: "/opt/release-bot/source"
      - name: Restart Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            systemctl stop release-bot
            mv /opt/release-bot/source/release-bot-latest.jar /opt/release-bot/source/release-bot-old.jar || true
            mv /opt/release-bot/source/release-bot.jar /opt/release-bot/source/release-bot-latest.jar
            systemctl start release-bot
            rm /opt/release-bot/source/release-bot-old.jar || true
