name: "Build and deploy application"
on:
  push:
    branches:
      - master
      - release
      - main
jobs:
  build_and_publish:
    name: Deploy and restart
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v1

      - name: Setup java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build jar
        run: mvn clean package

      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "release-bot.jar"
          target: "/opt/release-bot/source"

